apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: library/busybox:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: busybox-service
spec:
  type: NodePort
  selector:
    app: busybox
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31010
