apiVersion: apps/v1
kind: Deployment
metadata:
  name: dad-jokes-deployment
  labels:
    app: dad-jokes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dad-jokes
  template:
    metadata:
      labels:
        app: dad-jokes
    spec:
      containers:
      - name: dad-jokes
        image: jonahirande/dad-jokes-service:1.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: dad-jokes-service
spec:
  selector:
    app: dad-jokes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080 
  type: NodePort

