pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "<your-dockerhub-username>/dad-jokes-service:1.0"
        K8S_NAMESPACE = "default"
    }

    stages {
        stage('Build') {
            steps {
                script {
                    sh 'docker build -t $DOCKER_IMAGE .'
                }
            }
        }

        stage('Push') {
            steps {
                script {
                    sh 'docker login -u $DOCKER_USER -p $DOCKER_PASSWORD'
                    sh 'docker push $DOCKER_IMAGE'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh 'kubectl apply -f dad-jokes-deployment.yaml'
                }
            }
        }
    }
}

